const REVIEW_STATUSES = Object.freeze({
  PENDING_REVIEW: 'PENDING_REVIEW',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  APPROVED_ACTION: 'APPROVED_ACTION',
  REJECTED_SAFE: 'REJECTED_SAFE',
  ESCALATED: 'ESCALATED'
});

const RISK_CATEGORIES = Object.freeze({
  LOW_RISK: 'LOW_RISK',
  MEDIUM_RISK: 'MEDIUM_RISK',
  HIGH_RISK: 'HIGH_RISK',
  CRITICAL_RISK: 'CRITICAL_RISK'
});

const FINGERPRINT_STATUSES = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
});

const UPLOAD_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED',
  ARCHIVED: 'ARCHIVED'
});

const DETECTION_STATUSES = Object.freeze({
  CANDIDATE: 'CANDIDATE',
  MATCHED: 'MATCHED',
  DISMISSED: 'DISMISSED',
  NEEDS_REVIEW: 'NEEDS_REVIEW'
});

module.exports = {
  REVIEW_STATUSES,
  RISK_CATEGORIES,
  FINGERPRINT_STATUSES,
  UPLOAD_STATUSES,
  DETECTION_STATUSES
};
